# CircleCI Firebase Deployment Config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2.4-always-
            - npm-v2.7-{{ checksum "gatsby/package-lock.json" }}
      - run:
          name: Install Dependencies
          command: |
            cd  ~/build/gatsby
            npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "gatsby/package-lock.json" }}
          paths:
            - gatsby/node_modules
      - run:
          name: Gatsby Build
          command: |
            cd  ~/build/gatsby
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./

  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/build
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Serve Gatsby
          command: |
            cd ~/build/gatsby
            ./node_modules/gatsby/node_modules/.bin/gatsby serve 
          background: true
      - run:
          name: Wait...
          command: |
            dockerize -wait tcp://localhost:9000
      - run:
          name: Test links
          command: |
            cd ~/build
            bash ./scripts/link-checker.sh
      - save_cache:
          key: npm-v2.7-{{ checksum "gatsby/package-lock.json" }}
          paths:
            - ~/build/gatsby/package-lock.json
            - ~/build/gatsby/node_modules
      - save_cache:
          key: v2.4-always-{{ epoch }}
          paths:
            - ~/build/gatsby/public
            - ~/build/gatsby/.cache

  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/build
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Firebase Deploy
          command: ~/build/gatsby/node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

  preview:
    docker:
      - image: google/cloud-sdk
        environment:
          STORAGE_BUCKET: pr-000.artifactor.io
    working_directory: ~/build
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Login to gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: list files
          command: ls ~/build/gatsby/public
      - run:
          name: Deploy preview to GCP Storage
          command: | 
            echo "Copying build to Storage"
            gsutil defacl ch -u AllUsers:READER gs://$STORAGE_BUCKET
            gsutil rsync -R ~/build/gatsby/public gs://$STORAGE_BUCKET
            gsutil setmeta -h "Cache-Control:private, max-age=0, no-transform" \
            gs://$STORAGE_BUCKET/*.js

workflows:
  version: 2
  build-test-preview-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
      - preview:
          filters:
            branches:
              ignore: master
          requires:
            - build
